// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5883.Automatic.commands.drivetrain;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc5883.Automatic.Robot;

public class StraightDrive extends Command {

	private double driveStraightDistance;

    public StraightDrive(double driveStraightDistance) {
        this.driveStraightDistance = driveStraightDistance;
        
        requires(Robot.driveTrain);

    }

    protected void initialize() {
    	Robot.driveTrain.resetGyro();
    	Robot.driveTrain.resetEncoder();
    }

    protected void execute() {
   	Robot.driveTrain.driveStraight(0.5, 1);
    	    	
    }

    protected boolean isFinished() {
    	boolean isDrove = Robot.driveTrain.getDistanceInMeters() > driveStraightDistance;
        return isDrove;
    }

    protected void end() {
    	Robot.driveTrain.stopDrive();
    }

    protected void interrupted() {
    	end();
    }
}
